import { prisma } from "@/lib/prisma";

export type AuditAction =
  | "STUDENT_CREATED" | "STUDENT_UPDATED" | "STUDENT_DELETED"
  | "TEACHER_CREATED" | "TEACHER_UPDATED" | "TEACHER_DELETED"
  | "TEACHER_SOFT_DELETED" | "TEACHER_RESTORED" | "TEACHER_REASSIGNED"
  | "TEACHER_ROLE_ASSIGNED" | "TEACHER_ROLE_UNASSIGNED"
  | "TEACHER_CUSTOM_ROLE_UPDATED" | "TEACHER_CUSTOM_ROLE_DELETED"
  | "MARKS_SUBMITTED"
  | "LEAVE_APPROVED" | "LEAVE_REJECTED"
  | "EARLY_LEAVE_APPROVED" | "EARLY_LEAVE_REJECTED"
  | "ARRANGEMENTS_AUTO_GENERATED"
  | "FEE_PAYMENT_RECORDED"
  | "FEE_STRUCTURE_CREATED" | "FEE_STRUCTURE_DELETED"
  | "STUDENT_TRANSFERRED"
  | "GUARDIAN_UPSERTED"
  | "ANNOUNCEMENT_CREATED" | "ANNOUNCEMENT_UPDATED" | "ANNOUNCEMENT_DELETED"
  | "ANNOUNCEMENT_PUBLISHED" | "ANNOUNCEMENT_CORRECTED" | "ANNOUNCEMENT_CANCELLED" | "ANNOUNCEMENT_ARCHIVED"
  | "HOLIDAY_CREATED" | "HOLIDAY_DELETED"
  | "HOMEWORK_CREATED" | "HOMEWORK_UPDATED" | "HOMEWORK_CANCELLED" | "HOMEWORK_REVIEWED"
  | "HOMEWORK_COMPLETION_UPDATED"
  | "HOMEWORK_PUBLISHED" | "HOMEWORK_CLOSED" | "HOMEWORK_DUPLICATED" | "HOMEWORK_BULK_CHECKED"
  | "NOTEBOOK_CHECK_UPDATED"
  | "EXAM_MILESTONE_CREATED" | "EXAM_MILESTONE_UPDATED" | "EXAM_MILESTONE_DISABLED"
  | "ATTENDANCE_MARKED"
  | "ATTENDANCE_SUBMITTED"
  | "ATTENDANCE_ADMIN_CORRECTED"
  | "ATTENDANCE_CORRECTION_REQUESTED" | "ATTENDANCE_CORRECTION_APPROVED" | "ATTENDANCE_CORRECTION_REJECTED"
  | "REPORT_CARD_GENERATED" | "REPORT_CARD_PUBLISHED" | "REPORT_CARD_DOWNLOADED"
  | "PAYMENT_PROOF_SUBMITTED" | "PAYMENT_PROOF_APPROVED" | "PAYMENT_PROOF_REJECTED"
  | "SCHOOL_STATUS_CHANGED"
  | "SUBSCRIPTION_UPDATED"
  | "PLAN_CREATED" | "PLAN_UPDATED"
  | "INVITE_CREATED" | "INVITE_RESENT" | "INVITE_CANCELLED" | "INVITE_ACCEPTED"
  | "LOGIN_SUCCESS" | "LOGIN_FAILED"
  | "PASSWORD_RESET_REQUESTED" | "PASSWORD_RESET_COMPLETED"
  | "SCHOOL_CREATED"
  | "SCHOOL_DELETION_SCHEDULED" | "SCHOOL_DELETION_CANCELLED"
  | "SCHOOL_PURGE_STARTED" | "SCHOOL_PURGE_COMPLETED" | "SCHOOL_PURGE_FAILED"
  | "FOUNDER_INVITE_CREATED" | "FOUNDER_INVITE_RESENT" | "FOUNDER_INVITE_CANCELLED"
  | "SUBJECT_CREATED" | "SUBJECT_UPDATED" | "SUBJECT_DELETED"
  | "TIMETABLE_AUTO_RESOLVED"
  | "SMART_TIMETABLE_PUBLISHED"
  | "TEACHER_OPERATIONS_CHAIN_UPDATED"
  | "ADMISSION_CYCLE_CREATED" | "ADMISSION_CYCLE_UPDATED" | "ADMISSION_CYCLE_STATUS_CHANGED"
  | "ADMISSION_OFFERING_CREATED" | "ADMISSION_OFFERING_UPDATED"
  | "ADMISSION_APPLICATION_CREATED" | "ADMISSION_APPLICATION_UPDATED"
  | "ADMISSION_APPLICATION_SUBMITTED" | "ADMISSION_APPLICATION_TRANSITIONED"
  | "ADMISSION_APPLICATION_ENROLLED"
  | "ADMISSION_DOCUMENT_UPLOADED" | "ADMISSION_DOCUMENT_VERIFIED"
  | "ADMISSION_REVIEW_EVENT_CREATED" | "ADMISSION_REVIEW_EVENT_UPDATED"
  | "ADMISSION_NOTE_CREATED"
  | "LIBRARY_BOOK_CREATED" | "LIBRARY_BOOK_UPDATED" | "LIBRARY_BOOK_ARCHIVED" | "LIBRARY_BOOK_RESTORED"
  | "LIBRARY_COPY_ADDED" | "LIBRARY_COPY_STATUS_CHANGED"
  | "LIBRARY_BOOK_ISSUED" | "LIBRARY_BOOK_RETURNED" | "LIBRARY_LOAN_RENEWED"
  | "LIBRARY_RESERVATION_CREATED" | "LIBRARY_RESERVATION_CANCELLED"
  | "LIBRARY_RESERVATION_FULFILLED" | "LIBRARY_RESERVATION_EXPIRED"
  | "LIBRARY_FINE_ASSESSED" | "LIBRARY_FINE_WAIVED"
  | "LIBRARY_POLICY_CHANGED"
  | "TRANSPORT_ROUTE_CREATED" | "TRANSPORT_ROUTE_UPDATED" | "TRANSPORT_ROUTE_DELETED"
  | "TRANSPORT_STOP_CREATED"
  | "TRANSPORT_VEHICLE_CREATED" | "TRANSPORT_VEHICLE_UPDATED" | "TRANSPORT_VEHICLE_DELETED"
  | "TRANSPORT_DRIVER_CREATED" | "TRANSPORT_DRIVER_UPDATED" | "TRANSPORT_DRIVER_DELETED"
  | "TRANSPORT_ROUTE_ASSIGNMENT_CHANGED"
  | "TRANSPORT_STUDENT_ASSIGNMENT_CHANGED";

export async function logAudit({
  action,
  entityType,
  entityId,
  metadata,
  userId,
  schoolId,
  actorRole,
  ipAddress,
}: {
  action: AuditAction;
  entityType: string;
  entityId?: string;
  metadata?: Record<string, unknown>;
  userId: string;
  schoolId?: string | null;
  actorRole?: string | null;
  ipAddress?: string | null;
}) {
  try {
    await prisma.auditLog.create({
      data: {
        action,
        entityType,
        entityId: entityId ?? null,
        metadata: metadata ? JSON.stringify(metadata) : null,
        userId,
        schoolId: schoolId ?? null,
        actorRole: actorRole ?? null,
        ipAddress: ipAddress ?? null,
      },
    });
  } catch (err) {
    console.error("Audit log failed:", err);
  }
}
