import type { TemplateSnapshot } from "@/lib/report-card-templates";

type ReportCardPdfInput = {
  schoolName: string;
  logoUrl?: string | null;
  studentName: string;
  rollNo: string;
  classSection: string;
  examName: string;
  rank?: number | null;
  subjects: { subject: string; marks: number; maxMarks: number; grade: string; subjectTeacherRemark?: string | null }[];
  totalMarks: number;
  percentage: number;
  grade: string;
  attendance: {
    totalDays: number;
    presentDays: number;
    absentDays: number;
    lateDays: number;
    percentage: number | null;
  };
  classTeacherRemark?: string | null;
  generatedBy: string;
  publishedAt?: string | null;
  /** When present, rendering honors the template's branding/layout/section toggles. */
  template?: TemplateSnapshot | null;
};

export function generateReportCardPdf(input: ReportCardPdfInput) {
  const t = input.template;
  const landscape = t?.paperSize === "A4_LANDSCAPE";
  // A4: 595x842 portrait, swapped for landscape.
  const pageWidth = landscape ? 842 : 595;
  const pageHeight = landscape ? 595 : 842;
  const layoutLabel = t ? `${t.layoutType} layout` : "Default layout";

  const lines: string[] = [input.schoolName];

  // Branding references (image embedding is out of scope for the lightweight
  // PDF writer, so asset URLs are surfaced as references).
  const logo = t?.logoUrl ?? input.logoUrl;
  if (logo) lines.push(`Logo: ${logo}`);
  if (t?.backgroundImageUrl) lines.push(`Background: ${t.backgroundImageUrl}`);
  if (t?.watermarkText) lines.push(`[ Watermark: ${t.watermarkText} ]`);

  lines.push(t ? `Final Report Card — ${layoutLabel}` : "Final Report Card", "");

  lines.push(
    `Student: ${input.studentName}`,
    `Roll No: ${input.rollNo}`,
    `Class/Section: ${input.classSection}`,
    `Exam: ${input.examName}`,
  );
  // Rank is opt-in via the template.
  if ((!t || t.showRank) && typeof input.rank === "number") {
    lines.push(`Rank: ${input.rank}`);
  }
  lines.push("");

  const showGrade = !t || t.showGrade;
  lines.push(
    showGrade
      ? "Subject                          Marks        Grade"
      : "Subject                          Marks",
  );
  for (const subject of input.subjects) {
    const base = `${subject.subject.padEnd(30).slice(0, 30)} ${String(subject.marks).padStart(5)} / ${String(subject.maxMarks).padEnd(5)}`;
    lines.push(showGrade ? `${base} ${subject.grade}` : base);
    if (t?.showSubjectTeacherRemarks && subject.subjectTeacherRemark) {
      lines.push(`    Teacher: ${subject.subjectTeacherRemark}`);
    }
  }
  lines.push("");

  lines.push(`Total: ${input.totalMarks}`, `Percentage: ${input.percentage}%`);
  if (showGrade) lines.push(`Grade: ${input.grade}`);

  // Grade band legend from the template.
  if (t && t.showGrade && t.gradeBands.length > 0) {
    lines.push("Grading: " + t.gradeBands.map((b) => `${b.label} (${b.min}-${b.max})`).join("  "));
  }

  if (!t || t.showAttendance) {
    lines.push(
      `Attendance: ${input.attendance.presentDays}/${input.attendance.totalDays} present (${input.attendance.percentage ?? "N/A"}%)`,
      `Absent: ${input.attendance.absentDays}, Late: ${input.attendance.lateDays}`,
    );
  }
  lines.push("");

  // Custom sections (co-curricular / skills / discipline / awards / custom fields).
  if (t) {
    const sectionVisible: Record<string, boolean> = {
      "co-curricular": t.showCoCurricular,
      cocurricular: t.showCoCurricular,
      skills: t.showSkills,
      discipline: t.showDiscipline,
      awards: t.showAwards,
    };
    if (t.showCustomFields || t.showCoCurricular || t.showSkills || t.showDiscipline || t.showAwards) {
      for (const section of t.customSections) {
        const key = section.key.toLowerCase();
        const visible = key in sectionVisible ? sectionVisible[key] : t.showCustomFields;
        if (!visible) continue;
        lines.push(`${section.title}:`);
        for (const field of section.fields) {
          lines.push(`  ${field.label}: ${field.value}`);
        }
        lines.push("");
      }
    }
  }

  if ((!t || t.showRemarks) && (!t || t.showClassTeacherRemarks)) {
    lines.push(`Class Teacher Remark: ${input.classTeacherRemark || "N/A"}`);
  }
  lines.push(`Generated By: ${input.generatedBy}`);
  if (input.publishedAt) lines.push(`Published At: ${input.publishedAt}`);
  lines.push("");

  // Signatures.
  if (!t || t.classTeacherSignatureEnabled) {
    lines.push("Class Teacher Signature: __________________");
  }
  lines.push("Principal Signature: ______________________");
  if (t?.principalSignatureUrl) lines.push(`Principal Signature Image: ${t.principalSignatureUrl}`);
  if (t?.stampUrl) lines.push(`School Stamp: ${t.stampUrl}`);

  // Footer.
  if (t?.footerText) {
    lines.push("", t.footerText);
  }

  const startY = pageHeight - 62;
  const content = [
    "BT",
    "/F1 16 Tf",
    `54 ${startY} Td`,
    `(${escapePdfText(lines[0])}) Tj`,
    "/F1 10 Tf",
    ...lines.slice(1).map((line) => `0 -18 Td\n(${escapePdfText(line)}) Tj`),
    "ET",
  ].join("\n");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, "utf8");
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}
