type ReportCardPdfInput = {
  schoolName: string;
  logoUrl?: string | null;
  studentName: string;
  rollNo: string;
  classSection: string;
  examName: string;
  subjects: { subject: string; marks: number; maxMarks: number; grade: string }[];
  totalMarks: number;
  percentage: number;
  grade: string;
  attendance: {
    totalDays: number;
    presentDays: number;
    absentDays: number;
    lateDays: number;
    percentage: number | null;
  };
  classTeacherRemark?: string | null;
  generatedBy: string;
  publishedAt?: string | null;
};

export function generateReportCardPdf(input: ReportCardPdfInput) {
  const lines = [
    input.schoolName,
    ...(input.logoUrl ? [`Logo: ${input.logoUrl}`] : []),
    "Final Report Card",
    "",
    `Student: ${input.studentName}`,
    `Roll No: ${input.rollNo}`,
    `Class/Section: ${input.classSection}`,
    `Exam: ${input.examName}`,
    "",
    "Subject                          Marks        Grade",
    ...input.subjects.map((subject) =>
      `${subject.subject.padEnd(30).slice(0, 30)} ${String(subject.marks).padStart(5)} / ${String(subject.maxMarks).padEnd(5)} ${subject.grade}`
    ),
    "",
    `Total: ${input.totalMarks}`,
    `Percentage: ${input.percentage}%`,
    `Grade: ${input.grade}`,
    `Attendance: ${input.attendance.presentDays}/${input.attendance.totalDays} present (${input.attendance.percentage ?? "N/A"}%)`,
    `Absent: ${input.attendance.absentDays}, Late: ${input.attendance.lateDays}`,
    "",
    `Class Teacher Remark: ${input.classTeacherRemark || "N/A"}`,
    `Generated By: ${input.generatedBy}`,
    ...(input.publishedAt ? [`Published At: ${input.publishedAt}`] : []),
    "",
    "Class Teacher Signature: __________________",
    "Principal Signature: ______________________",
  ];

  const content = [
    "BT",
    "/F1 16 Tf",
    "54 780 Td",
    `(${escapePdfText(lines[0])}) Tj`,
    "/F1 10 Tf",
    ...lines.slice(1).map((line) => `0 -18 Td\n(${escapePdfText(line)}) Tj`),
    "ET",
  ].join("\n");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, "utf8");
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}
