# ── schoolsync-github-staging-deploy ────────────────────────────────────
#
# Assumed only via the GitHub Environment OIDC subject (`environment:staging`),
# not a branch ref — this is what makes required-reviewer/protected-branch
# GitHub Environment rules the actual gate on who can trigger a deployment,
# not just who can push to `staging`. Permissions are limited to the existing
# staging deployment: task-definition registration, web/worker service
# updates + stability reads, one-off migration run + result reads, the exact
# three existing ECS execution/task roles via scoped iam:PassRole, and
# read/lock-only access to the staging Terraform backend for the
# pre-mutation no-change gate. It cannot create/delete RDS, Redis, VPC, ALB,
# security groups, IAM roles, or secrets, and it cannot read a secret VALUE
# anywhere in this policy.

data "aws_iam_policy_document" "deploy_trust" {
  statement {
    sid     = "GithubActionsStagingEnvironmentOidc"
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [local.oidc_provider_arn]
    }

    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:aud"
      values   = ["sts.amazonaws.com"]
    }

    # Exact GitHub Environment subject — not a branch ref, not
    # `repo:OWNER/REPO:*`, not a wildcard anywhere in owner/repo/environment.
    # This ties the role to whatever protection rules the `staging`
    # Environment has configured (required reviewer, branch restriction —
    # see the repo-root runbook), independent of the build role's branch-ref
    # trust.
    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:sub"
      values   = ["repo:${var.github_repository_owner}/${var.github_repository_name}:environment:${var.github_environment}"]
    }
  }
}

resource "aws_iam_role" "github_staging_deploy" {
  name                 = "schoolsync-github-staging-deploy"
  description          = "Assumed via GitHub OIDC only from the '${var.github_environment}' GitHub Environment. ECS deploy + Terraform no-change read/lock only - no infrastructure mutation, no secret-value reads."
  assume_role_policy   = data.aws_iam_policy_document.deploy_trust.json
  max_session_duration = 3600

  lifecycle {
    precondition {
      condition = alltrue([
        !strcontains(var.github_repository_owner, "*"),
        !strcontains(var.github_repository_name, "*"),
        !strcontains(var.github_environment, "*"),
      ])
      error_message = "Wildcard repository/environment trust is not permitted for schoolsync-github-staging-deploy — every one of github_repository_owner/github_repository_name/github_environment must be an exact value."
    }
  }
}

locals {
  ecs_cluster_arn        = "arn:aws:ecs:${var.aws_region}:${var.aws_account_id}:cluster/${var.ecs_cluster_name}"
  ecs_web_service_arn    = "arn:aws:ecs:${var.aws_region}:${var.aws_account_id}:service/${var.ecs_cluster_name}/${var.ecs_web_service_name}"
  ecs_worker_service_arn = "arn:aws:ecs:${var.aws_region}:${var.aws_account_id}:service/${var.ecs_cluster_name}/${var.ecs_worker_service_name}"
  # Covers the web/worker/migrate task-definition families
  # (schoolsync-staging-web / -worker / -migrate), all of any revision.
  ecs_task_definition_arn_pattern = "arn:aws:ecs:${var.aws_region}:${var.aws_account_id}:task-definition/schoolsync-staging-*"
  log_group_arn_pattern           = "arn:aws:logs:${var.aws_region}:${var.aws_account_id}:log-group:/ecs/schoolsync-staging/*"

  ecs_execution_role_arn    = "arn:aws:iam::${var.aws_account_id}:role/${var.ecs_execution_role_name}"
  ecs_task_web_role_arn     = "arn:aws:iam::${var.aws_account_id}:role/${var.ecs_task_web_role_name}"
  ecs_task_minimal_role_arn = "arn:aws:iam::${var.aws_account_id}:role/${var.ecs_task_minimal_role_name}"

  # Bucket name is auto-generated by the app stack when s3_bucket_name is
  # left blank — "project-environment-account_id" (see
  # infra/terraform/variables.tf / s3.tf). This prefix pattern matches that
  # default without hardcoding the account-id suffix here.
  app_s3_bucket_arn_pattern = "arn:aws:s3:::schoolsync-staging-*"

  secrets_manager_secret_arn_pattern = "arn:aws:secretsmanager:${var.aws_region}:${var.aws_account_id}:secret:schoolsync-staging/app-*"
}

data "aws_iam_policy_document" "deploy_permissions" {
  # ecs:RegisterTaskDefinition / DescribeTaskDefinition do not support
  # resource-level permissions — the ECS IAM service reference lists both
  # as "*"-only actions. Scope is instead enforced by (a) iam:PassRole below
  # only trusting the three exact execution/task roles this stack already
  # has, and (b) this role's own trust policy only being assumable from the
  # `${var.github_environment}` GitHub Environment.
  statement {
    sid    = "EcsTaskDefinitionRegistration"
    effect = "Allow"
    actions = [
      "ecs:RegisterTaskDefinition",
      "ecs:DescribeTaskDefinition",
    ]
    resources = ["*"]
  }

  statement {
    sid       = "EcsServiceUpdateAndStabilityReads"
    effect    = "Allow"
    actions   = ["ecs:UpdateService", "ecs:DescribeServices"]
    resources = [local.ecs_web_service_arn, local.ecs_worker_service_arn]
  }

  statement {
    sid       = "EcsMigrationRunTask"
    effect    = "Allow"
    actions   = ["ecs:RunTask"]
    resources = [local.ecs_task_definition_arn_pattern]
    condition {
      test     = "ArnEquals"
      variable = "ecs:cluster"
      values   = [local.ecs_cluster_arn]
    }
  }

  statement {
    sid     = "EcsTaskResultReads"
    effect  = "Allow"
    actions = ["ecs:DescribeTasks", "ecs:ListTasks"]
    # DescribeTasks/ListTasks resource-level permissions are scoped via the
    # ecs:cluster condition key (task/task-instance ARNs are not knowable in
    # advance for a one-off run-task), not a resource ARN pattern.
    resources = ["*"]
    condition {
      test     = "ArnEquals"
      variable = "ecs:cluster"
      values   = [local.ecs_cluster_arn]
    }
  }

  statement {
    sid     = "PassExecutionAndTaskRolesToEcsTasksOnly"
    effect  = "Allow"
    actions = ["iam:PassRole"]
    resources = [
      local.ecs_execution_role_arn,
      local.ecs_task_web_role_arn,
      local.ecs_task_minimal_role_arn,
    ]
    condition {
      test     = "StringEquals"
      variable = "iam:PassedToService"
      values   = ["ecs-tasks.amazonaws.com"]
    }
  }

  statement {
    sid    = "EcrReadForDeployVerification"
    effect = "Allow"
    actions = [
      "ecr:BatchGetImage",
      "ecr:DescribeImages",
      "ecr:DescribeImageScanFindings",
      "ecr:GetDownloadUrlForLayer",
      "ecr:BatchCheckLayerAvailability",
    ]
    resources = ["arn:aws:ecr:${var.aws_region}:${var.aws_account_id}:repository/${var.ecr_repository_name}"]
  }

  statement {
    sid       = "EcrAuthToken"
    effect    = "Allow"
    actions   = ["ecr:GetAuthorizationToken"]
    resources = ["*"] # AWS requires "*" for this action — see the build role's identical justification.
  }

  statement {
    sid    = "CloudWatchLogsReadForPostDeployVerification"
    effect = "Allow"
    actions = [
      "logs:GetLogEvents",
      "logs:FilterLogEvents",
      "logs:DescribeLogStreams",
      "logs:DescribeLogGroups",
    ]
    resources = [local.log_group_arn_pattern]
  }

  statement {
    sid       = "TerraformStateReadOnly"
    effect    = "Allow"
    actions   = ["s3:GetObject"]
    resources = ["arn:aws:s3:::${var.terraform_state_bucket}/${var.terraform_state_key}"]
  }

  statement {
    sid       = "TerraformStateBucketListForRefresh"
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = ["arn:aws:s3:::${var.terraform_state_bucket}"]
    condition {
      test     = "StringLike"
      variable = "s3:prefix"
      values   = [var.terraform_state_key]
    }
  }

  statement {
    sid    = "TerraformStateLock"
    effect = "Allow"
    # DynamoDB lock acquire/release for `terraform plan` — this is "lock
    # access", not a state WRITE: the lock table holds only a lease record
    # (who/when), never the state itself. No s3:PutObject is granted
    # anywhere in this policy — this role can never persist a state change,
    # i.e. it can never run `terraform apply`.
    actions   = ["dynamodb:GetItem", "dynamodb:PutItem", "dynamodb:DeleteItem"]
    resources = ["arn:aws:dynamodb:${var.aws_region}:${var.aws_account_id}:table/${var.terraform_lock_table}"]
  }

  # ── Read-only "terraform plan" state-refresh reads ───────────────────────
  # A real `terraform plan` against the staging stack's ~20 .tf files must
  # refresh EVERY resource it manages (VPC/subnets/SGs, ALB, RDS,
  # ElastiCache, S3, Route53/ACM, SES, CloudWatch alarms/log groups, Cloud
  # Map, IAM roles) to detect drift — this is what "read-only infrastructure
  # checks needed for a Terraform no-change gate" requires in practice. Every
  # action below is a read verb (Describe/Get/List) only; none of it can
  # create, modify, or delete anything, and secretsmanager:GetSecretValue is
  # deliberately never granted anywhere in this policy (see
  # TerraformPlanSecretsMetadataOnly below — metadata only). Most of these
  # services do not support resource-level IAM conditions on their
  # Describe/List/Get actions (documented in the IAM service authorization
  # reference), so Resource: "*" is required here — the blast radius is
  # bounded by (a) every action being read-only, (b) this role's own trust
  # policy (assumable only from the `${var.github_environment}` GitHub
  # Environment), and (c) no destructive/write action appearing anywhere in
  # this policy.
  statement {
    sid    = "TerraformPlanReadOnlyRefresh"
    effect = "Allow"
    actions = [
      "ec2:Describe*",
      "elasticloadbalancing:Describe*",
      "rds:Describe*",
      "rds:ListTagsForResource",
      "elasticache:Describe*",
      "route53:GetHostedZone",
      "route53:ListResourceRecordSets",
      "acm:DescribeCertificate",
      "acm:ListTagsForCertificate",
      "ses:GetIdentityVerificationAttributes",
      "ses:GetIdentityDkimAttributes",
      "ses:ListIdentities",
      "cloudwatch:DescribeAlarms",
      "sns:GetTopicAttributes",
      "sns:ListTagsForResource",
      "logs:DescribeLogGroups",
      "servicediscovery:GetNamespace",
      "servicediscovery:GetService",
      "servicediscovery:ListNamespaces",
      "servicediscovery:ListServices",
      "ecs:DescribeClusters",
      "ecr:DescribeRepositories",
    ]
    resources = ["*"]
  }

  statement {
    sid    = "TerraformPlanIamRoleReadOnly"
    effect = "Allow"
    actions = [
      "iam:GetRole",
      "iam:GetRolePolicy",
      "iam:ListRolePolicies",
      "iam:ListAttachedRolePolicies",
      "iam:GetPolicy",
      "iam:GetPolicyVersion",
    ]
    resources = [
      local.ecs_execution_role_arn,
      local.ecs_task_web_role_arn,
      local.ecs_task_minimal_role_arn,
      "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
    ]
  }

  statement {
    sid    = "TerraformPlanSecretsMetadataOnly"
    effect = "Allow"
    # DescribeSecret returns metadata only (ARN, rotation config, version
    # stage labels) — never the secret value. GetSecretValue is
    # intentionally never granted to this role anywhere in this file.
    actions   = ["secretsmanager:DescribeSecret"]
    resources = [local.secrets_manager_secret_arn_pattern]
  }

  statement {
    sid    = "TerraformPlanS3BucketReadOnly"
    effect = "Allow"
    actions = [
      "s3:GetBucketAcl",
      "s3:GetBucketPolicy",
      "s3:GetBucketVersioning",
      "s3:GetBucketTagging",
      "s3:GetBucketCors",
      "s3:GetBucketLogging",
      "s3:GetBucketWebsite",
      "s3:GetEncryptionConfiguration",
      "s3:GetLifecycleConfiguration",
      "s3:GetBucketPublicAccessBlock",
      "s3:GetBucketOwnershipControls",
      "s3:ListBucket",
    ]
    resources = [local.app_s3_bucket_arn_pattern]
  }

  # No ecs:CreateService / DeleteService / DeleteCluster, no rds:Create*
  # /Modify*/Delete*, no elasticache:Create*/Modify*/Delete*, no
  # ec2:CreateVpc*/CreateSecurityGroup*/*, no iam:CreateRole/DeleteRole/
  # Put*RolePolicy/AttachRolePolicy, no secretsmanager:PutSecretValue/
  # RotateSecret/DeleteSecret, no route53:Change*, no s3:PutBucket*/
  # DeleteBucket* — this role is structurally incapable of infrastructure
  # mutation or secret-value retrieval. An actual `terraform apply` against
  # the staging stack (which would additionally need broad WRITE
  # permissions across every one of those services) stays a manual,
  # schoolsync-admin-profile operation — see infra/terraform/README.md and
  # the repo-root CI/CD runbook.
}

resource "aws_iam_role_policy" "github_staging_deploy" {
  name   = "schoolsync-github-staging-deploy-ecs-and-tf-readonly"
  role   = aws_iam_role.github_staging_deploy.id
  policy = data.aws_iam_policy_document.deploy_permissions.json
}
