# ── Environment-scoped GitHub deploy role ───────────────────────────────
#
# Assumed only via the exact configured GitHub Environment OIDC subject,
# not a branch ref — this is what makes required-reviewer/protected-branch
# GitHub Environment rules the actual gate on who can trigger a deployment,
# not just who can push to a branch. Permissions are limited to the selected
# deployment: task-definition registration, web/worker service
# updates + stability reads, one-off migration run + result reads, the exact
# three existing ECS execution/task roles via scoped iam:PassRole, and
# read/lock-only access to the selected Terraform backend for the
# pre-mutation no-change gate. It cannot create/delete RDS, Redis, VPC, ALB,
# security groups, IAM roles, or secrets, and it cannot read a secret VALUE
# anywhere in this policy.

data "aws_iam_policy_document" "deploy_trust" {
  statement {
    sid     = "GithubActionsStagingEnvironmentOidc"
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [local.oidc_provider_arn]
    }

    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:aud"
      values   = ["sts.amazonaws.com"]
    }

    # Exact GitHub Environment subject — not a branch ref, not
    # `repo:OWNER/REPO:*`, not a wildcard anywhere in owner/repo/environment.
    # This ties the role to whatever protection rules the configured
    # Environment has configured (required reviewer, branch restriction —
    # see the repo-root runbook), independent of the build role's branch-ref
    # trust.
    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:sub"
      values   = ["repo:${var.github_repository_owner}/${var.github_repository_name}:environment:${var.github_environment}"]
    }
  }
}

resource "aws_iam_role" "github_staging_deploy" {
  name                 = "${var.project_name}-github-${var.deployment_environment}-deploy"
  description          = "Assumed via GitHub OIDC only from the '${var.github_environment}' GitHub Environment. ECS deploy + Terraform no-change read/lock only - no infrastructure mutation, no secret-value reads."
  assume_role_policy   = data.aws_iam_policy_document.deploy_trust.json
  max_session_duration = 3600

  lifecycle {
    precondition {
      condition = alltrue([
        !strcontains(var.github_repository_owner, "*"),
        !strcontains(var.github_repository_name, "*"),
        !strcontains(var.github_environment, "*"),
      ])
      error_message = "Wildcard repository/environment trust is not permitted for the GitHub deploy role."
    }
    precondition {
      condition     = var.github_environment == var.deployment_environment
      error_message = "github_environment must exactly match deployment_environment."
    }
  }
}

locals {
  ecs_cluster_arn        = "arn:aws:ecs:${var.aws_region}:${var.aws_account_id}:cluster/${var.ecs_cluster_name}"
  ecs_web_service_arn    = "arn:aws:ecs:${var.aws_region}:${var.aws_account_id}:service/${var.ecs_cluster_name}/${var.ecs_web_service_name}"
  ecs_worker_service_arn = "arn:aws:ecs:${var.aws_region}:${var.aws_account_id}:service/${var.ecs_cluster_name}/${var.ecs_worker_service_name}"
  # Covers web/worker/migrate task-definition families for this exact
  # environment, all revisions.
  application_name_prefix         = "${var.project_name}-${var.deployment_environment}"
  ecs_task_definition_arn_pattern = "arn:aws:ecs:${var.aws_region}:${var.aws_account_id}:task-definition/${local.application_name_prefix}-*"
  log_group_arn_pattern           = "arn:aws:logs:${var.aws_region}:${var.aws_account_id}:log-group:/ecs/${local.application_name_prefix}/*"

  ecs_execution_role_arn           = "arn:aws:iam::${var.aws_account_id}:role/${var.ecs_execution_role_name}"
  ecs_task_web_role_arn            = "arn:aws:iam::${var.aws_account_id}:role/${var.ecs_task_web_role_name}"
  ecs_task_minimal_role_arn        = "arn:aws:iam::${var.aws_account_id}:role/${var.ecs_task_minimal_role_name}"
  eventbridge_maintenance_role_arn = "arn:aws:iam::${var.aws_account_id}:role/${var.eventbridge_maintenance_role_name}"

  # Bucket name is auto-generated by the app stack when s3_bucket_name is
  # left blank — "project-environment-account_id" (see
  # infra/terraform/variables.tf / s3.tf). This prefix pattern matches that
  # default without hardcoding the account-id suffix here.
  app_s3_bucket_arn_pattern = "arn:aws:s3:::${local.application_name_prefix}-*"

  secrets_manager_secret_arn_pattern = "arn:aws:secretsmanager:${var.aws_region}:${var.aws_account_id}:secret:${local.application_name_prefix}/app-*"

  # Exact ARNs for every CloudWatch alarm the app stack's terraform plan
  # refreshes (confirmed against the deployed alarms) — enumerated, not a
  # wildcard, per this role's exact-scoping requirement.
  cloudwatch_alarm_arns = [
    "arn:aws:cloudwatch:${var.aws_region}:${var.aws_account_id}:alarm:${local.application_name_prefix}-alb-unhealthy-targets",
    "arn:aws:cloudwatch:${var.aws_region}:${var.aws_account_id}:alarm:${local.application_name_prefix}-alb-5xx",
    "arn:aws:cloudwatch:${var.aws_region}:${var.aws_account_id}:alarm:${local.application_name_prefix}-rds-cpu",
    "arn:aws:cloudwatch:${var.aws_region}:${var.aws_account_id}:alarm:${local.application_name_prefix}-rds-low-storage",
    "arn:aws:cloudwatch:${var.aws_region}:${var.aws_account_id}:alarm:${local.application_name_prefix}-rds-connections",
  ]

  # Exact ElastiCache subnet group ARN for this stack.
  elasticache_subnet_group_arn = "arn:aws:elasticache:${var.aws_region}:${var.aws_account_id}:subnetgroup:${local.application_name_prefix}-redis"
}

data "aws_iam_policy_document" "deploy_permissions" {
  # ecs:RegisterTaskDefinition / DescribeTaskDefinition do not support
  # resource-level permissions — the ECS IAM service reference lists both
  # as "*"-only actions. Scope is instead enforced by (a) iam:PassRole below
  # only trusting the three exact execution/task roles this stack already
  # has, and (b) this role's own trust policy only being assumable from the
  # `${var.github_environment}` GitHub Environment.
  statement {
    sid    = "EcsTaskDefinitionRegistration"
    effect = "Allow"
    actions = [
      "ecs:RegisterTaskDefinition",
      "ecs:DescribeTaskDefinition",
    ]
    resources = ["*"]
  }

  statement {
    sid       = "EcsServiceUpdateAndStabilityReads"
    effect    = "Allow"
    actions   = ["ecs:UpdateService", "ecs:DescribeServices"]
    resources = [local.ecs_web_service_arn, local.ecs_worker_service_arn]
  }

  statement {
    sid       = "EcsMigrationRunTask"
    effect    = "Allow"
    actions   = ["ecs:RunTask"]
    resources = [local.ecs_task_definition_arn_pattern]
    condition {
      test     = "ArnEquals"
      variable = "ecs:cluster"
      values   = [local.ecs_cluster_arn]
    }
  }

  statement {
    sid     = "EcsTaskResultReads"
    effect  = "Allow"
    actions = ["ecs:DescribeTasks", "ecs:ListTasks"]
    # DescribeTasks/ListTasks resource-level permissions are scoped via the
    # ecs:cluster condition key (task/task-instance ARNs are not knowable in
    # advance for a one-off run-task), not a resource ARN pattern.
    resources = ["*"]
    condition {
      test     = "ArnEquals"
      variable = "ecs:cluster"
      values   = [local.ecs_cluster_arn]
    }
  }

  statement {
    sid     = "PassExecutionAndTaskRolesToEcsTasksOnly"
    effect  = "Allow"
    actions = ["iam:PassRole"]
    resources = [
      local.ecs_execution_role_arn,
      local.ecs_task_web_role_arn,
      local.ecs_task_minimal_role_arn,
    ]
    condition {
      test     = "StringEquals"
      variable = "iam:PassedToService"
      values   = ["ecs-tasks.amazonaws.com"]
    }
  }

  statement {
    sid    = "EcrReadForDeployVerification"
    effect = "Allow"
    actions = [
      "ecr:BatchGetImage",
      "ecr:DescribeImages",
      "ecr:DescribeImageScanFindings",
      "ecr:GetDownloadUrlForLayer",
      "ecr:BatchCheckLayerAvailability",
      # Required for the app stack's terraform plan to refresh this
      # repository's tags (same resource this statement already scopes).
      "ecr:ListTagsForResource",
    ]
    resources = ["arn:aws:ecr:${var.aws_region}:${var.aws_account_id}:repository/${var.ecr_repository_name}"]
  }

  statement {
    sid       = "EcrAuthToken"
    effect    = "Allow"
    actions   = ["ecr:GetAuthorizationToken"]
    resources = ["*"] # AWS requires "*" for this action — see the build role's identical justification.
  }

  statement {
    sid    = "CloudWatchLogsReadForPostDeployVerification"
    effect = "Allow"
    actions = [
      "logs:GetLogEvents",
      "logs:FilterLogEvents",
      "logs:DescribeLogStreams",
      "logs:DescribeLogGroups",
      # Required for the app stack's terraform plan to refresh these log
      # groups' tags (same resource pattern this statement already scopes).
      "logs:ListTagsForResource",
    ]
    resources = [local.log_group_arn_pattern]
  }

  statement {
    sid       = "TerraformStateReadOnly"
    effect    = "Allow"
    actions   = ["s3:GetObject"]
    resources = ["arn:aws:s3:::${var.terraform_state_bucket}/${var.terraform_state_key}"]
  }

  statement {
    sid       = "TerraformStateBucketListForRefresh"
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = ["arn:aws:s3:::${var.terraform_state_bucket}"]
    condition {
      test     = "StringLike"
      variable = "s3:prefix"
      values   = [var.terraform_state_key]
    }
  }

  statement {
    sid    = "TerraformStateLock"
    effect = "Allow"
    # DynamoDB lock acquire/release for `terraform plan` — this is "lock
    # access", not a state WRITE: the lock table holds only a lease record
    # (who/when), never the state itself. No s3:PutObject is granted
    # anywhere in this policy — this role can never persist a state change,
    # i.e. it can never run `terraform apply`. DescribeTable (read-only
    # table metadata, not item data) is required for the pre-mutation
    # preflight's own `aws dynamodb describe-table` existence probe.
    actions   = ["dynamodb:GetItem", "dynamodb:PutItem", "dynamodb:DeleteItem", "dynamodb:DescribeTable"]
    resources = ["arn:aws:dynamodb:${var.aws_region}:${var.aws_account_id}:table/${var.terraform_lock_table}"]
  }

  # ── Read-only "terraform plan" state-refresh reads ───────────────────────
  # A real `terraform plan` against the application stack's .tf files must
  # refresh EVERY resource it manages (VPC/subnets/SGs, ALB, RDS,
  # ElastiCache, S3, Route53/ACM, SES, CloudWatch alarms/log groups, Cloud
  # Map, IAM roles) to detect drift — this is what "read-only infrastructure
  # checks needed for a Terraform no-change gate" requires in practice. Every
  # action below is a read verb (Describe/Get/List) only; none of it can
  # create, modify, or delete anything, and secretsmanager:GetSecretValue is
  # deliberately never granted anywhere in this policy (see
  # TerraformPlanSecretsMetadataOnly below — metadata only). Most of these
  # services do not support resource-level IAM conditions on their
  # Describe/List/Get actions (documented in the IAM service authorization
  # reference), so Resource: "*" is required here — the blast radius is
  # bounded by (a) every action being read-only, (b) this role's own trust
  # policy (assumable only from the `${var.github_environment}` GitHub
  # Environment), and (c) no destructive/write action appearing anywhere in
  # this policy.
  statement {
    sid    = "TerraformPlanReadOnlyRefresh"
    effect = "Allow"
    actions = [
      "ec2:Describe*",
      "elasticloadbalancing:Describe*",
      "rds:Describe*",
      "rds:ListTagsForResource",
      "elasticache:Describe*",
      "route53:GetHostedZone",
      "route53:ListResourceRecordSets",
      "acm:DescribeCertificate",
      "acm:ListTagsForCertificate",
      "ses:GetIdentityVerificationAttributes",
      "ses:GetIdentityDkimAttributes",
      "ses:ListIdentities",
      "cloudwatch:DescribeAlarms",
      "sns:GetTopicAttributes",
      "sns:ListTagsForResource",
      "logs:DescribeLogGroups",
      "servicediscovery:GetNamespace",
      "servicediscovery:GetService",
      "servicediscovery:ListNamespaces",
      "servicediscovery:ListServices",
      "ecs:DescribeClusters",
      "ecr:DescribeRepositories",
      "events:DescribeApiDestination",
      "events:DescribeConnection",
      "events:DescribeRule",
      "events:ListTargetsByRule",
      "events:ListTagsForResource",
    ]
    resources = ["*"]
  }

  statement {
    sid    = "TerraformPlanIamRoleReadOnly"
    effect = "Allow"
    actions = [
      "iam:GetRole",
      "iam:GetRolePolicy",
      "iam:ListRolePolicies",
      "iam:ListAttachedRolePolicies",
      "iam:GetPolicy",
      "iam:GetPolicyVersion",
    ]
    resources = [
      local.ecs_execution_role_arn,
      local.ecs_task_web_role_arn,
      local.ecs_task_minimal_role_arn,
      local.eventbridge_maintenance_role_arn,
      "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
    ]
  }

  statement {
    sid    = "TerraformPlanSecretsMetadataOnly"
    effect = "Allow"
    # DescribeSecret/GetResourcePolicy both return metadata only (ARN,
    # rotation config, version stage labels / the resource policy document
    # itself) — never the secret VALUE. GetSecretValue is intentionally
    # never granted to this role anywhere in this file.
    actions   = ["secretsmanager:DescribeSecret", "secretsmanager:GetResourcePolicy"]
    resources = [local.secrets_manager_secret_arn_pattern]
  }

  statement {
    sid    = "TerraformPlanS3BucketReadOnly"
    effect = "Allow"
    actions = [
      "s3:GetBucketAcl",
      "s3:GetBucketPolicy",
      "s3:GetBucketVersioning",
      "s3:GetBucketTagging",
      "s3:GetBucketCors",
      "s3:GetBucketLogging",
      "s3:GetBucketWebsite",
      "s3:GetEncryptionConfiguration",
      "s3:GetLifecycleConfiguration",
      "s3:GetBucketPublicAccessBlock",
      "s3:GetBucketOwnershipControls",
      "s3:ListBucket",
      # Required for the app stack's terraform plan to refresh this
      # bucket's transfer-acceleration setting (same resource pattern this
      # statement already scopes).
      "s3:GetAccelerateConfiguration",
    ]
    resources = [local.app_s3_bucket_arn_pattern]
  }

  statement {
    # HeadBucket's own IAM check (used by the pre-mutation preflight's
    # `aws s3api head-bucket` existence probe) requires s3:ListBucket on the
    # bucket with no s3:prefix in the request context at all — HeadBucket
    # has no prefix parameter to send. The StringLike condition on
    # TerraformStateBucketListForRefresh above therefore never matches a
    # HeadBucket call (a missing condition key evaluates the condition as
    # false), so that statement alone always denies it. This is a separate,
    # unconditional grant of the same action for that reason alone — it
    # does not additionally grant any object-level access (no plain
    # s3:GetObject here), so the practical exposure is bucket-existence +
    # object-key enumeration of this one state bucket, not state content.
    # Appended last (not inserted between existing statements) so this
    # addition doesn't shift the position of any other statement in the
    # generated JSON list — keeps the Terraform plan diff to exactly this
    # one addition plus the TerraformStateLock action-list change above.
    sid       = "TerraformStateBucketHeadBucketPreflight"
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = ["arn:aws:s3:::${var.terraform_state_bucket}"]
  }

  statement {
    # Required for the app stack's terraform plan to refresh each alarm's
    # tags. Appended last (not inserted between existing statements) so
    # this addition doesn't shift the position of any other statement in
    # the generated JSON list.
    sid       = "TerraformPlanCloudWatchAlarmTagsReadOnly"
    effect    = "Allow"
    actions   = ["cloudwatch:ListTagsForResource"]
    resources = local.cloudwatch_alarm_arns
  }

  statement {
    # Required for the app stack's terraform plan to refresh the ElastiCache
    # subnet group's tags.
    sid       = "TerraformPlanElastiCacheTagsReadOnly"
    effect    = "Allow"
    actions   = ["elasticache:ListTagsForResource"]
    resources = [local.elasticache_subnet_group_arn]
  }

  statement {
    # Required for the app stack's terraform plan to refresh the Cloud Map
    # private DNS namespace's tags. servicediscovery:ListTagsForResource has
    # no resource type in AWS Cloud Map's IAM service authorization
    # reference — it does not support resource-level (namespace-ARN)
    # scoping at all, so Resource: "*" is required here, not a gap in this
    # statement's scoping. (An earlier version of this statement scoped it
    # to the exact namespace ARN; that grant was silently ineffective for
    # this reason and has been replaced by this dedicated, single-action
    # wildcard statement — see the PR history for how this was confirmed.)
    # No other action is combined into this statement.
    sid       = "TerraformPlanServiceDiscoveryTagsReadOnly"
    effect    = "Allow"
    actions   = ["servicediscovery:ListTagsForResource"]
    resources = ["*"]
  }

  # No ecs:CreateService / DeleteService / DeleteCluster, no rds:Create*
  # /Modify*/Delete*, no elasticache:Create*/Modify*/Delete*, no
  # ec2:CreateVpc*/CreateSecurityGroup*/*, no iam:CreateRole/DeleteRole/
  # Put*RolePolicy/AttachRolePolicy, no secretsmanager:PutSecretValue/
  # RotateSecret/DeleteSecret, no route53:Change*, no s3:PutBucket*/
  # DeleteBucket* — this role is structurally incapable of infrastructure
  # mutation or secret-value retrieval. An actual `terraform apply` against
  # the application stack (which would additionally need broad WRITE
  # permissions across every one of those services) stays a manual,
  # schoolsync-admin-profile operation — see infra/terraform/README.md and
  # the repo-root CI/CD runbook.
}

resource "aws_iam_role_policy" "github_staging_deploy" {
  name   = "${var.project_name}-github-${var.deployment_environment}-deploy-ecs-and-tf-readonly"
  role   = aws_iam_role.github_staging_deploy.id
  policy = data.aws_iam_policy_document.deploy_permissions.json
}
